# Generated by Django 4.2 on 2025-04-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScraperConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='設定名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('urls', models.TextField(verbose_name='スクレイピング対象URL（JSON形式）')),
                ('additional_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='追加URL')),
                ('require_login', models.BooleanField(default=False, verbose_name='ログインが必要')),
                ('username_selector', models.CharField(blank=True, max_length=255, null=True, verbose_name='ユーザー名セレクタ')),
                ('password_selector', models.CharField(blank=True, max_length=255, null=True, verbose_name='パスワードセレクタ')),
                ('login_button_selector', models.CharField(blank=True, max_length=255, null=True, verbose_name='ログインボタンセレクタ')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='ユーザー名')),
                ('password', models.CharField(blank=True, max_length=255, null=True, verbose_name='パスワード')),
                ('extraction_selectors', models.TextField(verbose_name='抽出セレクタ（JSON形式）')),
                ('use_text_mode', models.BooleanField(default=False, verbose_name='文字列モード')),
                ('use_pagination', models.BooleanField(default=False, verbose_name='ページネーションを使用')),
                ('next_button_selector', models.CharField(blank=True, max_length=255, null=True, verbose_name='次へボタンセレクタ')),
                ('max_pages', models.IntegerField(default=1, verbose_name='最大ページ数')),
                ('download_images', models.BooleanField(default=False, verbose_name='画像をダウンロード')),
                ('image_selector', models.CharField(blank=True, max_length=255, null=True, verbose_name='画像セレクタ')),
                ('output_path', models.CharField(default='output', max_length=255, verbose_name='出力パス')),
            ],
        ),
    ]
